apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: TQC Python System
spec:
  description: TQC Python Practice System with Next.js, Nest.js, and MongoDB
  variables:
    #   - key: JWT_SECRET
    #     type: STRING
    #     name: JWT Secret
    #     description: Secret key for JWT authentication
    #   - key: GEMINI_API_KEY
    #     type: STRING
    #     name: Gemini API Key
    #     description: API Key for Google Gemini
    #   - key: GOOGLE_CLIENT_ID
    #     type: STRING
    #     name: Google Client ID
    #     description: Google OAuth Client ID
    #   - key: GOOGLE_CLIENT_SECRET
    #     type: STRING
    #     name: Google Client Secret
    #     description: Google OAuth Client Secret
    #   - key: GOOGLE_CALLBACK_URL
    #     type: STRING
    #     name: Google Callback URL
    #     description: Google OAuth Callback URL
    #   - key: FRONTEND_URL
    #     type: STRING
    #     name: Frontend URL
    #     description: URL of the frontend application (e.g. https://your-app.zeabur.app)
    #   - key: NODE_ENV
    #     type: STRING
    #     name: Node Environment
    #     description: Environment (production/development)

    - key: MONGODB_URI
      type: STRING
      name: MongoDB Connection URI
      description: Connection string for MongoDB (e.g. from Zeabur Marketplace)

  services:
    - name: backend
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 1135388322
          branch: master
          rootDirectory: .
          dockerfile: backend/Dockerfile
        ports:
          - id: http
            port: 3001
            type: HTTP

    - name: frontend
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 1135388322
          branch: master
          rootDirectory: .
          dockerfile: frontend/Dockerfile
        ports:
          - id: http
            port: 3000
            type: HTTP
      dependencies:
        - backend

    - name: nginx
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 1135388322
          branch: master
          rootDirectory: .
          dockerfile: nginx/Dockerfile
        ports:
          - id: http
            port: 80
            type: HTTP
      dependencies:
        - frontend
        - backend
